import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "../theme/ThemeProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignInUrl="/onboarding" afterSignUpUrl="/onboarding">
      <html lang="en">
        <ThemeProvider>
          <body className={`${inter.variable} antialiased`}>
            {children}
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
